version: '3'

services:
  app:
    image: paidy/forex:1.0.1
    restart: on-failure
    ports:
      - "8888:8888"
    environment:
      ONE_FRAME_HOST: http://one-frame:8080
    links:
      - one-frame
  one-frame:
    image: paidyinc/one-frame
    ports:
      - "8080:8080"